title: Jeffrey Ochavillo
logo: "/images/logo.png?raw=true"
description: |
  <b>Aspiring Data Scientist/Analyst/Engineer</b>
  <br><br>
  Seattle-based, Guam-raised<br>
  Master of Data Science, Bachelor of Mathematics @ Seattle University
  <br><br>
  <li><a href="https://www.linkedin.com/in/jeffrey-ochavillo/" class="icon brands fa-linkedin"><span class="label">LinkedIn</span></a></li>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0
